# Generated by Django 4.0.5 on 2022-06-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Mr', 'Mr')], max_length=50)),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('user_name', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
