# Generated by Django 4.0.5 on 2022-06-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_delete_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Mr', 'Mr')], max_length=50),
        ),
    ]
