# Generated by Django 4.0.5 on 2022-06-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Ms', 'Ms'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss')], max_length=50),
        ),
    ]
