# Generated by Django 4.0.6 on 2022-07-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_transaction', models.DateTimeField()),
                ('type_of_transaction', models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal')], max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=100000000000000)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('account', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='create_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, default='', max_length=60)),
                ('First_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Last_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Starting_Balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=100000000000000)),
            ],
        ),
    ]
