# Generated by Django 4.0.6 on 2022-07-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Last_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Starting_Balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=100000000000000)),
            ],
        ),
        migrations.RenameModel(
            old_name='account_information',
            new_name='Information',
        ),
        migrations.DeleteModel(
            name='create_Account',
        ),
    ]
