# Generated by Django 4.0.6 on 2022-07-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_account_rename_account_information_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Account',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
