# Generated by Django 4.0.6 on 2022-07-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_account_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Account',
        ),
    ]
