# Generated by Django 4.0.6 on 2022-07-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_account_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Account',
        ),
        migrations.AlterField(
            model_name='information',
            name='type_of_transaction',
            field=models.CharField(choices=[('withdrawal', 'withdrawal'), ('deposit', 'deposit')], max_length=60),
        ),
    ]
